### ISSUE TITLE
Trace Generation Automatically

### ISSUE THREAD

**Issue by baichen318** [microsoft/calipers#1]
Hi all,

I wondered if a convenient method exists for us to generate sample traces with respect to the predefined formats from the GEM5 simulation.

Should we write the script manually to generate such traces for different test cases?

Thank you very much.

Best regards,
Chen

**Comment by hosseingolestani** [comment]
Hi Chen,

Using gem5 to generate traces in Calipers' format requires some changes in gem5's source. We might provide a patch for gem5 as well as a gem5 simulation object that controls trace generation in the future. But here are pointers to where gem5 should be modified:
- Disassembled instructions
    - [`Trace::ExeTracerRecord::traceInst`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/exetrace.cc#61) (The `Exec` debug flag must be used in order for this function to execute.)
    - `pc.instAddr()`: instruction address, `inst->disassemble(...)`: disassembled instruction, `addr`: memory address (for loads/stores)
    - Note: Instruction disassembly can be done wherever there exists a dynamic instance of an instruction, i.e., using `instruction->staticInst->disassemble(...)`.

More pointers if you also need gem5 for memory and branch prediction information:
- Fetch cycles
    - [`Fetch1::fetchLine`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/minor/fetch1.cc#156) and [`Fetch1::recvTimingResp`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/minor/fetch1.cc#418) for the in-order core
    - [`Fetch::fetchCacheLine`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/fetch.cc#554) and [`Fetch::processCacheCompletion`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/fetch.cc#351) for the out-of-order core
    - Use `curTick()` to obtain start and end cycles of fetch requests in the function pairs above.
- Branch prediction outcome (correct/incorrect)
    - [`Fetch2::updateBranchPrediction`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/minor/fetch2.cc#130) for the in-order core
    - [`IEW::executeInsts`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/iew.cc#1136) and [`IEW::checkMisprediction`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/iew.cc#1592) for the out-order core
- Memory access cycles
    - [`Execute::executeMemRefInst`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/minor/execute.cc#451) and [`Execute::commit`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/minor/execute.cc#895) for the in-order core
    - [`LSQ::insertLoad`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/lsq.cc#221)/[`LSQ::insertStore`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/lsq.cc#229) and [`LSQ::completeDataAccess`](https://gem5.googlesource.com/public/gem5/+/refs/tags/v22.0.0.1/src/cpu/o3/lsq.cc#395) for the out-order core
    - Use `curTick()` to obtain start and end cycles of memory requests in the function pairs above.

Thanks,
Hossein

**Comment by baichen318** [comment]
Hi Hossein @hosseingolestani,

Thanks very much for your information.

Best regards,
Chen
